export const SET_USERNAME = 'SET_USERNAME';
export type SET_USERNAME = typeof SET_USERNAME;

export const SET_PROFILE_PICTURE_URL = 'SET_PROFILE_PICTURE_URL';
export type SET_PROFILE_PICTURE_URL = typeof SET_PROFILE_PICTURE_URL;

export const SET_PROFILE_INFO = 'SET_PROFILE_INFO';
export type SET_PROFILE_INFO = typeof SET_PROFILE_INFO;
